In [12]:
import pandas as pd

xml_pat = pd.read_csv('../data/grant2012_all.csv')

In [4]:
citation = pd.read_csv("../data/citations.csv")

In [13]:
xml_pat.head()

   Unnamed: 0   parsed
0         539  8166569
1         540  8166570
2         541  8166571
3         542  8166572
4         543  8166573

In [15]:
xml_pat.drop('Unnamed: 0', axis=1)

         parsed
0       8166569
1       8166570
2       8166571
3       8166572
4       8166573
5       8166574
6       8166575
7       8166576
8       8166577
9       8166578
10      8166579
11      8166580
12      8166581
13      8166582
14      8166583
15      8166584
16      8166585
17      8166586
18      8166587
19      8166588
20      8166589
21      8166590
22      8166591
23      8166592
24      8166593
25      8166594
26      8166595
27      8166596
28      8166597
29      8166598
...         ...
253610  8291482
253611  8291483
253612  8291484
253613  8291485
253614  8291486
253615  8291487
253616  8291488
253617  8291489
253618  8291490
253619  8291491
253620  8291492
253621  8291493
253622  8291494
253623  8291495
253624  8291496
253625  8291497
253626  8291498
253627  8291499
253628  8291500
253629  8291501
253630  8291502
253631  8291503
253632  8291504
253633  8291505
253634  8291506
253635  8291507
253636  8291508
253637  8291509
253638  8291510
253639  8291511

[253640 rows x 1 columns]

In [31]:
citation

,app_id,citation_pat_pgpub_id,parsed,ifw_number,action_type,action_subtype,form892,form1449,citation_in_oa
0,12000001,20060218340,20060218340,NaN,NaN,NaN,0,1,0
1,12000001,2343564,2343564,NaN,NaN,NaN,1,0,0
2,12000001,6622200,6622200,NaN,NaN,NaN,1,0,0
3,12000001,6182004,6182004,NaN,NaN,NaN,0,1,0
4,12000001,2323432,2323432,NaN,NaN,NaN,1,0,0
5,12000001,5694538,5694538,NaN,NaN,NaN,1,0,0
6,12000001,2333454,2333454,NaN,NaN,NaN,1,0,0
7,12000001,20040088473,20040088473,G92WF69VPPOPPY5,103.0,a,1,0,1
8,12000001,20030189860,20030189860,G92WF69VPPOPPY5,103.0,a,1,0,1
9,12000001,20050013154,20050013154,G92WF69VPPOPPY5,103.0,a,1,1,1
10,12000001,20050013154,20050013154,GCJ90TE3PPOPPY5,103.0,a,1,1,1
11,12000001,6883060,6883060,GCJ90TE3PPOPPY5,103.0,a,1,1,1
12,12000001,20040088473,20040088473,GCJ90TE3PPOPPY5,103.0,a,1,0,1
13,12000001,20030189860,20030189860,GCJ90TE3PPOPPY5,103.0,a,1,0,1
14,12000003,6163210,6163210,NaN,NaN,NaN,1,0,0
15,12000003,6232838,6232838,NaN,NaN,NaN,1,0,0
16,12000003,5999047,5999047,NaN,NaN,NaN,1,0,0
17,12000003,6011434,6011434,NaN,NaN,NaN,1,0,0
18,12000003,6774716,6774716,NaN,NaN,NaN,1,0,0
19,12000005,20080098205,20080098205,NaN,NaN,NaN,1,0,0
20,12000005,20070199046,20070199046,NaN,NaN,NaN,0,1,0
21,12000005,20050216701,20050216701,NaN,NaN,NaN,1,0,0
22,12000005,20060064546,20060064546,NaN,NaN,NaN,0,1,0
23,12000005,20060200802,20060200802,NaN,NaN,NaN,1,0,0
24,12000005,6684305,6684305,FZVAXT62PPOPPY5,102.0,b,1,0,1
25,12000005,20040215898,20040215898,FZVAXT62PPOPPY5,103.0,a,1,0,1
26,12000005,20080222383,20080222383,FZVAXT62PPOPPY5,103.0,a,1,0,1
27,12000005,6684305,6684305,FZVAXT62PPOPPY5,103.0,a,1,0,1
28,12000005,20030028751,20030028751,FZVAXT62PPOPPY5,103.0,a,1,0,1
29,12000006,20120223883,20120223883,NaN,NaN,NaN,1,0,0
...,...,...,...,...,...,...,...,...,...
58862248,15371637,"Lo et al US 2008/0236738, hereinafter",20080236738,IYVMGBQ3RXEAPX4,103.0,NaN,0,0,1
58862249,15371637,"Dudek US 5,167,989",5167989,IYVMGBQ3RXEAPX4,103.0,NaN,0,0,1
58862250,15371637,"Zhuang et al US 2013/0186514, hereinafter",20130186514,IYVMGBQ3RXEAPX4,103.0,NaN,0,0,1
58862251,15371637,"Larsson US 2006/0145381, hereinafter",20060145381,IYVMGBQ3RXEAPX4,103.0,NaN,0,0,1
58862252,15371649,Lazzarini US 2008/0314603,20080314603,IXTS8Z89RXEAPX5,102.0,b,0,0,1
58862253,15371663,Saidha US 2010/0094345,20100094345,IYVJDGHLRXEAPX2,102.0,b,0,0,1
58862254,15371669,US 2007/0119060,20070119060,IXHLUF0IRXEAPX5,103.0,NaN,0,0,1
58862255,15371669,"Afshari 6,560,884 B1",6560884,IXHLUF0IRXEAPX5,103.0,NaN,0,0,1
58862256,15371669,"Wilson US 5,996,569 A",5996569,IXHLUF0IRXEAPX5,103.0,NaN,0,0,1
58862257,15371680,"Kopshever U.S. Patent 7,849,659",7849659,J0MKCYY1RXEAPX3,102.0,a,0,0,1
58862258,15371680,"Kopshever U.S. Patent 7,849,659",7849659,J0MKCYY1RXEAPX3,103.0,NaN,0,0,1
58862259,15371747,Mitomo US6632379,6632379,J0JT3CO9RXEAPX2,103.0,a,0,0,1
58862260,15372103,"Le et al US 7,356,679",7356679,J0JZ0TG6RXEAPX1,103.0,a,0,0,1
58862261,15372103,"Kim et al US 7,334,227",7334227,J0JZ0TG6RXEAPX1,103.0,a,0,0,1
58862262,15372292,"Haas U.S. 2010/0332493, published 30 December ...",20100332493,IZYCZVDYRXEAPX3,102.0,a,0,0,1
58862263,15372309,"Wagnitz US PN. 6,112,460",6112460,IZZYFYP1RXEAPX2,103.0,NaN,0,0,1
58862264,15372312,Fujioka US 2014/0240378,20140240378,IXVT9JUWRXEAPX0,102.0,e,0,0,1
58862265,15372312,Okubo et al US 2004/0218401,20040218401,IXVT9JUWRXEAPX0,103.0,a,0,0,1
58862266,15372312,Fujioka US 2014/0240378,20140240378,IXVT9JUWRXEAPX0,103.0,a,0,0,1
58862267,15372540,Morf USPA 2008/0210085 A1,20080210085,IWZ6UM38RXEAPX1,102.0,b,0,0,1
58862268,15372540,"Noritake USPN 5,861,053",5861053,IWZ6UM38RXEAPX1,103.0,a,0,0,1
58862269,15372540,Morf USPA 2008/0210085 A1,20080210085,IWZ6UM38RXEAPX1,103.0,a,0,0,1
58862270,15372540,"Spokoyny USPN 5,320,052",5320052,IWZ6UM38RXEAPX1,103.0,a,0,0,1
58862271,15374996,Rousso et al U.S. pub No. 2009/0126320,20090126320,IZ9UQHN3RXEAPX5,102.0,a,0,0,1
58862272,15374996,"Finnestad U.S. Patent No. 8,505,769",8505769,IZ9UQHN3RXEAPX5,103.0,NaN,0,0,1
58862273,15374996,Rousso et al U.S. pub No. 2009/0126320,20090126320,IZ9UQHN3RXEAPX5,103.0,NaN,0,0,1
58862274,15374996,"Pierre U.S. Patent No. 7,516,865",7516865,IZ9UQHN3RXEAPX5,103.0,NaN,0,0,1
58862275,15378268,OSBORNE et al US 2006/0009835 A1,20060009835,J09WJFLJRXEAPX1,102.0,b,0,0,1
58862276,15378268,OSBORNE et al US 2006/0009835 A1,20060009835,J09WJFLJRXEAPX1,103.0,a,0,0,1
58862277,15378268,"CLARK et al US 4,191,218",4191218,J09WJFLJRXEAPX1,103.0,a,0,0,1

In [16]:
merge = pd.merge(citation, xml_pat, on = 'parsed')

In [17]:
merge

Empty DataFrame
Columns: [app_id, citation_pat_pgpub_id, parsed, ifw_number, action_type, action_subtype, form892, form1449, citation_in_oa, Unnamed: 0]
Index: []

In [18]:
type(citation['parsed'][0])

str

In [19]:
type(xml_pat['parsed'][0])

numpy.int64

In [22]:
xml_pat.astype('str')

       Unnamed: 0   parsed
0             539  8166569
1             540  8166570
2             541  8166571
3             542  8166572
4             543  8166573
5             544  8166574
6             545  8166575
7             546  8166576
8             547  8166577
9             548  8166578
10            549  8166579
11            550  8166580
12            551  8166581
13            552  8166582
14            553  8166583
15            554  8166584
16            555  8166585
17            556  8166586
18            557  8166587
19            558  8166588
20            559  8166589
21            560  8166590
22            561  8166591
23            562  8166592
24            563  8166593
25            564  8166594
26            565  8166595
27            566  8166596
28            567  8166597
29            568  8166598
...           ...      ...
253610     277254  8291482
253611     277255  8291483
253612     277256  8291484
253613     277257  8291485
253614     277258  8291486
253615     277259  8291487
253616     277260  8291488
253617     277261  8291489
253618     277262  8291490
253619     277263  8291491
253620     277264  8291492
253621     277265  8291493
253622     277266  8291494
253623     277267  8291495
253624     277268  8291496
253625     277269  8291497
253626     277270  8291498
253627     277271  8291499
253628     277272  8291500
253629     277273  8291501
253630     277274  8291502
253631     277275  8291503
253632     277276  8291504
253633     277277  8291505
253634     277278  8291506
253635     277279  8291507
253636     277280  8291508
253637     277281  8291509
253638     277282  8291510
253639     277283  8291511

[253640 rows x 2 columns]

In [26]:
xml_pat = xml_pat.drop('Unnamed: 0', axis=1)

In [27]:
xml_pat_str = xml_pat.astype('str')

In [28]:
type(xml_pat_str['parsed'][0])

str

In [29]:
merge2 = pd.merge(citation, xml_pat_str, on = 'parsed')

In [30]:
merge2

,app_id,citation_pat_pgpub_id,parsed,ifw_number,action_type,action_subtype,form892,form1449,citation_in_oa
0,12000006,8116685,8116685,NaN,NaN,NaN,1,0,0
1,12861189,8116685,8116685,NaN,NaN,NaN,1,0,0
2,13105088,8116685,8116685,NaN,NaN,NaN,1,0,0
3,13301546,8116685,8116685,NaN,NaN,NaN,1,0,0
4,13651182,8116685,8116685,NaN,NaN,NaN,0,1,0
5,13660852,8116685,8116685,NaN,NaN,NaN,0,1,0
6,13663736,8116685,8116685,NaN,NaN,NaN,1,0,0
7,13718073,8116685,8116685,NaN,NaN,NaN,0,1,0
8,13725533,8116685,8116685,NaN,NaN,NaN,0,1,0
9,13792764,8116685,8116685,NaN,NaN,NaN,0,1,0
10,13827143,8116685,8116685,NaN,NaN,NaN,0,1,0
11,13846351,8116685,8116685,NaN,NaN,NaN,0,1,0
12,13873117,8116685,8116685,NaN,NaN,NaN,0,1,0
13,14162780,8116685,8116685,NaN,NaN,NaN,1,0,0
14,15173064,8116685,8116685,NaN,NaN,NaN,0,1,0
15,12000006,8112794,8112794,NaN,NaN,NaN,1,0,0
16,12090878,8112794,8112794,NaN,NaN,NaN,1,0,0
17,13276078,8112794,8112794,HPO1J525PXXIFW4,103.0,a,1,0,1
18,13276078,8112794,8112794,HV8227U1PXXIFW4,103.0,a,1,0,1
19,13288067,8112794,8112794,NaN,NaN,NaN,1,0,0
20,13448121,8112794,8112794,NaN,NaN,NaN,1,0,0
21,13571348,8112794,8112794,NaN,NaN,NaN,0,1,0
22,13727287,8112794,8112794,HY7MQ0WJPXXIFW4,103.0,a,1,0,1
23,13844145,8112794,8112794,NaN,NaN,NaN,0,1,0
24,13882935,8112794,8112794,NaN,NaN,NaN,1,0,0
25,14335887,8112794,8112794,NaN,NaN,NaN,1,0,0
26,14341166,8112794,8112794,NaN,NaN,NaN,1,1,0
27,14607820,8112794,8112794,NaN,NaN,NaN,1,1,0
28,14632850,8112794,8112794,NaN,NaN,NaN,0,1,0
29,14673095,8112794,8112794,IQMLKCHJRXEAPX5,103.0,NaN,1,0,1
...,...,...,...,...,...,...,...,...,...
885435,15286766,8180260,8180260,NaN,NaN,NaN,0,1,0
885436,15286851,8180260,8180260,NaN,NaN,NaN,0,1,0
885437,15293493,8180260,8180260,NaN,NaN,NaN,0,1,0
885438,15286880,8180483,8180483,NaN,NaN,NaN,0,1,0
885439,15289504,8228651,8228651,NaN,NaN,NaN,0,1,0
885440,15291700,8242147,8242147,NaN,NaN,NaN,0,1,0
885441,15294176,8337163,8337163,NaN,NaN,NaN,0,1,0
885442,15304355,8337163,8337163,NaN,NaN,NaN,0,1,0
885443,15294176,8251661,8251661,NaN,NaN,NaN,0,1,0
885444,15304355,8251661,8251661,NaN,NaN,NaN,0,1,0
885445,15294176,8162603,8162603,J0TKI50IRXEAPX4,102.0,a,0,1,1
885446,15294176,8162603,8162603,J0TKI50IRXEAPX4,103.0,NaN,0,1,1
885447,15304355,8162603,8162603,J02XLY0WRXEAPX5,103.0,NaN,0,1,1
885448,15295971,8135969,8135969,NaN,NaN,NaN,0,1,0
885449,15296418,8190235,8190235,NaN,NaN,NaN,1,0,0
885450,15298002,8339900,8339900,NaN,NaN,NaN,1,0,0
885451,15298057,8339900,8339900,NaN,NaN,NaN,1,0,0
885452,15300766,8283401,8283401,IVS6V5ZMRXEAPX1,102.0,a,1,0,1
885453,15300766,8283401,8283401,IVS6V5ZMRXEAPX1,103.0,NaN,1,0,1
885454,15304500,Guichard USP 8101279,8101279,J0DZ47J8RXEAPX1,103.0,NaN,0,0,1
885455,15311174,8242757,8242757,NaN,NaN,NaN,0,1,0
885456,15311174,8258705,8258705,NaN,NaN,NaN,0,1,0
885457,15311534,8227798,8227798,NaN,NaN,NaN,0,1,0
885458,15339257,"Daubenspeck et al USPAT 8,198,133 B2",8198133,IZIFBYH9RXEAPX1,102.0,b,0,0,1
885459,15339397,"Ueno US 8,270,274",8270274,IXUHD5V0RXEAPX5,102.0,a,0,0,1
885460,15339397,"Ueno US 8,270,274",8270274,IXUHD5V0RXEAPX5,103.0,a,0,0,1
885461,15344605,8224051,8224051,NaN,NaN,NaN,0,1,0
885462,15351591,8217287,8217287,NaN,NaN,NaN,0,1,0
885463,15352759,8208274,8208274,NaN,NaN,NaN,0,1,0
885464,15354151,8161091,8161091,NaN,NaN,NaN,0,1,0

In [47]:
merge2.to_csv('../data/grant2012_in_citations.csv')

In [1]:
import pandas as pd

app = pd.read_csv('../data/application2017_all.csv', index_col = 0)

In [2]:
app

          app_id
0       14988955
1       15299629
2       15239362
3       15462276
4       14998443
5       14989324
6       15394889
7       15468355
8       15397470
9       15389705
10      15315522
11      15376045
12      15394870
13      15400508
14      15320694
15      15388262
16      15466166
17      15066891
18      15038292
19      15115888
20      15338359
21      15400857
22      14985128
23      14988031
24      15144925
25      15386079
26      14987776
27      15062132
28      15404081
29      14989373
...          ...
373896  15498641
373897  15593917
373898  15591637
373899  15531932
373900  15155244
373901  15582708
373902  15419526
373903  15522429
373904  15481451
373905  15667032
373906  15291313
373907  15593168
373908  15150783
373909  15523185
373910  15153348
373911  15595194
373912  15535027
373913  15590591
373914  15526477
373915  15528161
373916  15664599
373917  15586544
373918  15291293
373919  15291348
373920  15627615
373921  15154461
373922  15533394
373923  15662399
373924  15583760
373925  15529761

[373926 rows x 1 columns]

In [5]:
merge3 = pd.merge(citation, app, on = 'app_id')

In [6]:
merge3

,app_id,citation_pat_pgpub_id,parsed,ifw_number,action_type,action_subtype,form892,form1449,citation_in_oa
0,12022531,20050240098,20050240098,NaN,NaN,NaN,0,1,0
1,12022531,20050148995,20050148995,NaN,NaN,NaN,0,1,0
2,12022531,5873827,5873827,NaN,NaN,NaN,1,0,0
3,12022531,6544185,6544185,NaN,NaN,NaN,1,0,0
4,12022531,6725083,6725083,NaN,NaN,NaN,1,0,0
5,12022531,7556602,7556602,NaN,NaN,NaN,1,0,0
6,12022531,20080208347,20080208347,NaN,NaN,NaN,0,1,0
7,12022531,20040042582,20040042582,NaN,NaN,NaN,1,0,0
8,12022531,20040030262,20040030262,NaN,NaN,NaN,1,0,0
9,12022531,8280486,8280486,NaN,NaN,NaN,1,0,0
10,12022531,7790141,7790141,NaN,NaN,NaN,1,0,0
11,12022531,5882557,5882557,NaN,NaN,NaN,1,0,0
12,12022531,6106473,6106473,NaN,NaN,NaN,1,0,0
13,12022531,20040030262,20040030262,GFSBRWFQPPOPPY5,102.0,b,1,0,1
14,12022531,6106473,6106473,GKK2WRXOPPOPPY5,103.0,a,1,0,1
15,12022531,20040030262,20040030262,GKK2WRXOPPOPPY5,103.0,a,1,0,1
16,12022531,5882557,5882557,GKK2WRXOPPOPPY5,103.0,a,1,0,1
17,12022531,20040030262,20040030262,GP7HC6GXPPOPPY5,103.0,a,1,0,1
18,12022531,6106473,6106473,GP7HC6GXPPOPPY5,103.0,a,1,0,1
19,12022531,5882557,5882557,GP7HC6GXPPOPPY5,103.0,a,1,0,1
20,12022531,5873827,5873827,GP7HC6GXPPOPPY5,103.0,a,1,0,1
21,12022531,5882557,5882557,GW7RWJWAPXXIFW4,103.0,a,1,0,1
22,12022531,20040030262,20040030262,GW7RWJWAPXXIFW4,103.0,a,1,0,1
23,12022531,6725083,6725083,GW7RWJWAPXXIFW4,103.0,a,1,0,1
24,12022531,20040030262,20040030262,H5XYOOEZPXXIFW4,103.0,a,1,0,1
25,12022531,6725083,6725083,H5XYOOEZPXXIFW4,103.0,a,1,0,1
26,12022531,5882557,5882557,H5XYOOEZPXXIFW4,103.0,a,1,0,1
27,12022531,6725083,6725083,HHJIXFJUPXXIFW4,103.0,a,1,0,1
28,12022531,20040030262,20040030262,HHJIXFJUPXXIFW4,103.0,a,1,0,1
29,12022531,5882557,5882557,HHJIXFJUPXXIFW4,103.0,a,1,0,1
...,...,...,...,...,...,...,...,...,...
278373,15371561,TAKAI et al pub No.: US 2007-0192786,0192786,IZ5MXF19RXEAPX3,103.0,a,0,0,1
278374,15371561,GRIFFIN et al pub No.: US 2013-0064524,0064524,IZ5MXF19RXEAPX3,103.0,a,0,0,1
278375,15371561,SMITH et al pub No.: US 2010-0033624,0033624,IZ5MXF19RXEAPX3,103.0,a,0,0,1
278376,15371637,"Lo et al US 2008/0236738, hereinafter",20080236738,IYVMGBQ3RXEAPX4,103.0,NaN,0,0,1
278377,15371637,"Dudek US 5,167,989",5167989,IYVMGBQ3RXEAPX4,103.0,NaN,0,0,1
278378,15371637,"Zhuang et al US 2013/0186514, hereinafter",20130186514,IYVMGBQ3RXEAPX4,103.0,NaN,0,0,1
278379,15371637,"Larsson US 2006/0145381, hereinafter",20060145381,IYVMGBQ3RXEAPX4,103.0,NaN,0,0,1
278380,15371649,Lazzarini US 2008/0314603,20080314603,IXTS8Z89RXEAPX5,102.0,b,0,0,1
278381,15371663,Saidha US 2010/0094345,20100094345,IYVJDGHLRXEAPX2,102.0,b,0,0,1
278382,15371669,US 2007/0119060,20070119060,IXHLUF0IRXEAPX5,103.0,NaN,0,0,1
278383,15371669,"Afshari 6,560,884 B1",6560884,IXHLUF0IRXEAPX5,103.0,NaN,0,0,1
278384,15371669,"Wilson US 5,996,569 A",5996569,IXHLUF0IRXEAPX5,103.0,NaN,0,0,1
278385,15371680,"Kopshever U.S. Patent 7,849,659",7849659,J0MKCYY1RXEAPX3,102.0,a,0,0,1
278386,15371680,"Kopshever U.S. Patent 7,849,659",7849659,J0MKCYY1RXEAPX3,103.0,NaN,0,0,1
278387,15371747,Mitomo US6632379,6632379,J0JT3CO9RXEAPX2,103.0,a,0,0,1
278388,15372103,"Le et al US 7,356,679",7356679,J0JZ0TG6RXEAPX1,103.0,a,0,0,1
278389,15372103,"Kim et al US 7,334,227",7334227,J0JZ0TG6RXEAPX1,103.0,a,0,0,1
278390,15372292,"Haas U.S. 2010/0332493, published 30 December ...",20100332493,IZYCZVDYRXEAPX3,102.0,a,0,0,1
278391,15372309,"Wagnitz US PN. 6,112,460",6112460,IZZYFYP1RXEAPX2,103.0,NaN,0,0,1
278392,15372312,Fujioka US 2014/0240378,20140240378,IXVT9JUWRXEAPX0,102.0,e,0,0,1
278393,15372312,Okubo et al US 2004/0218401,20040218401,IXVT9JUWRXEAPX0,103.0,a,0,0,1
278394,15372312,Fujioka US 2014/0240378,20140240378,IXVT9JUWRXEAPX0,103.0,a,0,0,1
278395,15372540,Morf USPA 2008/0210085 A1,20080210085,IWZ6UM38RXEAPX1,102.0,b,0,0,1
278396,15372540,"Noritake USPN 5,861,053",5861053,IWZ6UM38RXEAPX1,103.0,a,0,0,1
278397,15372540,Morf USPA 2008/0210085 A1,20080210085,IWZ6UM38RXEAPX1,103.0,a,0,0,1
278398,15372540,"Spokoyny USPN 5,320,052",5320052,IWZ6UM38RXEAPX1,103.0,a,0,0,1
278399,15374996,Rousso et al U.S. pub No. 2009/0126320,20090126320,IZ9UQHN3RXEAPX5,102.0,a,0,0,1
278400,15374996,"Finnestad U.S. Patent No. 8,505,769",8505769,IZ9UQHN3RXEAPX5,103.0,NaN,0,0,1
278401,15374996,Rousso et al U.S. pub No. 2009/0126320,20090126320,IZ9UQHN3RXEAPX5,103.0,NaN,0,0,1
278402,15374996,"Pierre U.S. Patent No. 7,516,865",7516865,IZ9UQHN3RXEAPX5,103.0,NaN,0,0,1

In [7]:
xml_pat = pd.read_csv('../data/grant2012_all.csv', index_col = 0)
xml_pat

         parsed
539     8166569
540     8166570
541     8166571
542     8166572
543     8166573
544     8166574
545     8166575
546     8166576
547     8166577
548     8166578
549     8166579
550     8166580
551     8166581
552     8166582
553     8166583
554     8166584
555     8166585
556     8166586
557     8166587
558     8166588
559     8166589
560     8166590
561     8166591
562     8166592
563     8166593
564     8166594
565     8166595
566     8166596
567     8166597
568     8166598
...         ...
277254  8291482
277255  8291483
277256  8291484
277257  8291485
277258  8291486
277259  8291487
277260  8291488
277261  8291489
277262  8291490
277263  8291491
277264  8291492
277265  8291493
277266  8291494
277267  8291495
277268  8291496
277269  8291497
277270  8291498
277271  8291499
277272  8291500
277273  8291501
277274  8291502
277275  8291503
277276  8291504
277277  8291505
277278  8291506
277279  8291507
277280  8291508
277281  8291509
277282  8291510
277283  8291511

[253640 rows x 1 columns]

In [15]:
xml_pat['parsed'].astype('str')

539       8166569
540       8166570
541       8166571
542       8166572
543       8166573
544       8166574
545       8166575
546       8166576
547       8166577
548       8166578
549       8166579
550       8166580
551       8166581
552       8166582
553       8166583
554       8166584
555       8166585
556       8166586
557       8166587
558       8166588
559       8166589
560       8166590
561       8166591
562       8166592
563       8166593
564       8166594
565       8166595
566       8166596
567       8166597
568       8166598
           ...
277254    8291482
277255    8291483
277256    8291484
277257    8291485
277258    8291486
277259    8291487
277260    8291488
277261    8291489
277262    8291490
277263    8291491
277264    8291492
277265    8291493
277266    8291494
277267    8291495
277268    8291496
277269    8291497
277270    8291498
277271    8291499
277272    8291500
277273    8291501
277274    8291502
277275    8291503
277276    8291504
277277    8291505
277278    8291506
277279    8291507
277280    8291508
277281    8291509
277282    8291510
277283    8291511
Name: parsed, Length: 253640, dtype: object

In [16]:
merge4 = pd.merge(merge3, xml_pat.astype('str'), on = 'parsed')

In [17]:
merge4

,app_id,citation_pat_pgpub_id,parsed,ifw_number,action_type,action_subtype,form892,form1449,citation_in_oa
0,12022531,8280486,8280486,NaN,NaN,NaN,1,0,0
1,12242637,8275762,8275762,NaN,NaN,NaN,0,1,0
2,12242637,8108415,8108415,NaN,NaN,NaN,0,1,0
3,12294889,8106092,8106092,NaN,NaN,NaN,0,1,0
4,12489066,8145522,8145522,NaN,NaN,NaN,0,1,0
5,12489066,8108492,8108492,NaN,NaN,NaN,0,1,0
6,12489066,8150767,8150767,NaN,NaN,NaN,0,1,0
7,13758472,8150767,8150767,NaN,NaN,NaN,0,1,0
8,12489066,8106766,8106766,NaN,NaN,NaN,0,1,0
9,12489066,8190522,8190522,NaN,NaN,NaN,0,1,0
10,12489066,8190893,8190893,NaN,NaN,NaN,0,1,0
11,14809464,8190893,8190893,NaN,NaN,NaN,1,0,0
12,12489066,8151335,8151335,NaN,NaN,NaN,0,1,0
13,12489066,8121948,8121948,NaN,NaN,NaN,0,1,0
14,12656252,8166418,8166418,NaN,NaN,NaN,0,1,0
15,12691506,8230610,8230610,NaN,NaN,NaN,0,1,0
16,12691506,8099124,8099124,NaN,NaN,NaN,0,1,0
17,12877115,8190452,8190452,NaN,NaN,NaN,0,1,0
18,12951946,8287928,8287928,NaN,NaN,NaN,0,1,0
19,13024953,8212201,8212201,HQ3SCW7IPXXIFW4,103.0,a,1,0,1
20,13053079,8110574,8110574,NaN,NaN,NaN,0,1,0
21,13104127,8202342,8202342,NaN,NaN,NaN,0,1,0
22,13104127,8105413,8105413,NaN,NaN,NaN,0,1,0
23,13186063,8298268,8298268,NaN,NaN,NaN,1,0,0
24,13186063,8298268,8298268,HCUM9NCSPXXIFW4,102.0,b,1,0,1
25,13186063,8298268,8298268,HCUM9NCSPXXIFW4,103.0,a,1,0,1
26,13186063,8298268,8298268,HKV3VYS7PXXIFW4,103.0,a,1,0,1
27,13186063,8298268,8298268,HU9X0Z3GPXXIFW4,103.0,a,1,0,1
28,13186063,8298275,8298275,NaN,NaN,NaN,1,0,0
29,13186063,8105356,8105356,NaN,NaN,NaN,1,0,0
...,...,...,...,...,...,...,...,...,...
6715,15362214,8113938,8113938,NaN,NaN,NaN,0,1,0
6716,15362214,8137193,8137193,NaN,NaN,NaN,0,1,0
6717,15362270,8215520,8215520,NaN,NaN,NaN,0,1,0
6718,15362270,8225946,8225946,NaN,NaN,NaN,0,1,0
6719,15362270,8276772,8276772,NaN,NaN,NaN,0,1,0
6720,15362270,8167149,8167149,NaN,NaN,NaN,0,1,0
6721,15362338,8184641,8184641,NaN,NaN,NaN,0,1,0
6722,15362338,8325706,8325706,NaN,NaN,NaN,0,1,0
6723,15362338,8089871,8089871,NaN,NaN,NaN,0,1,0
6724,15362372,8296138,8296138,NaN,NaN,NaN,0,1,0
6725,15362372,8326634,8326634,NaN,NaN,NaN,0,1,0
6726,15362372,8140327,8140327,NaN,NaN,NaN,0,1,0
6727,15362372,8265928,8265928,NaN,NaN,NaN,0,1,0
6728,15362385,8094045,8094045,NaN,NaN,NaN,0,1,0
6729,15362468,8270435,8270435,NaN,NaN,NaN,0,1,0
6730,15362484,8108367,8108367,NaN,NaN,NaN,0,1,0
6731,15363616,8212259,8212259,NaN,NaN,NaN,0,1,0
6732,15363686,8271334,8271334,NaN,NaN,NaN,0,1,0
6733,15363805,8214943,8214943,IWZ1Y9VNRXEAPX5,103.0,NaN,0,1,1
6734,15363903,8112312,8112312,NaN,NaN,NaN,0,1,0
6735,15363911,8213826,8213826,NaN,NaN,NaN,0,1,0
6736,15363919,8091100,8091100,NaN,NaN,NaN,0,1,0
6737,15363919,8194923,8194923,NaN,NaN,NaN,0,1,0
6738,15363919,8225342,8225342,NaN,NaN,NaN,0,1,0
6739,15363919,8302120,8302120,NaN,NaN,NaN,0,1,0
6740,15365570,Sauerwein et al 8205421,8205421,IX1WPL77RXEAPX4,102.0,a,0,0,1
6741,15365577,8215371,8215371,NaN,NaN,NaN,0,1,0
6742,15366036,"Kennedy et al US 8,305,196",8305196,IXL2BF4NRXEAPX2,103.0,NaN,0,0,1
6743,15368151,"Bennett U.S. Patent No. 8,200,649 B2",8200649,IXUFOPE8RXEAPX4,103.0,a,0,0,1
6744,15370294,"Violonchi 8,300,293",8300293,IXQ87CVQRXEAPX4,103.0,a,0,0,1

In [21]:
merge4[merge4['form892'] == 1].count()

app_id                   824
citation_pat_pgpub_id    824
parsed                   824
ifw_number               263
action_type              263
action_subtype           108
form892                  824
form1449                 824
citation_in_oa           824
dtype: int64

In [22]:
app.min()

app_id    10074825
dtype: int64

In [23]:
app.max()

app_id    15731929
dtype: int64