In [1]:
import os
import glob
import pandas as pd
import numpy as np

In [2]:
path_app = "../data/app_bib_2017"
path_grant = "../data/grant_bib_2012"

Files_app = glob.glob(os.path.join(path_app,"*.xml"))
Files_grant = glob.glob(os.path.join(path_grant,"*.xml"))

In [3]:
Files_app

['../data/app_bib_2017/ipab20170706.xml',
 '../data/app_bib_2017/ipab20171228.xml',
 '../data/app_bib_2017/ipab20171019.xml',
 '../data/app_bib_2017/ipab20171207.xml',
 '../data/app_bib_2017/ipab20170727.xml',
 '../data/app_bib_2017/ipab20170223.xml',
 '../data/app_bib_2017/ipab20170105.xml',
 '../data/app_bib_2017/ipab20170921.xml',
 '../data/app_bib_2017/ipab20171123.xml',
 '../data/app_bib_2017/ipab20170119.xml',
 '../data/app_bib_2017/ipab20170504.xml',
 '../data/app_bib_2017/ipab20171109.xml',
 '../data/app_bib_2017/ipab20170525.xml',
 '../data/app_bib_2017/ipab20170601.xml',
 '../data/app_bib_2017/ipab20170720.xml',
 '../data/app_bib_2017/ipab20170713.xml',
 '../data/app_bib_2017/ipab20170914.xml',
 '../data/app_bib_2017/ipab20170518.xml',
 '../data/app_bib_2017/ipab20170216.xml',
 '../data/app_bib_2017/ipab20170824.xml',
 '../data/app_bib_2017/ipab20170928.xml',
 '../data/app_bib_2017/ipab20170907.xml',
 '../data/app_bib_2017/ipab20170803.xml',
 '../data/app_bib_2017/ipab20171221.xml',
 '../data/app_bib_2017/ipab20170316.xml',
 '../data/app_bib_2017/ipab20170817.xml',
 '../data/app_bib_2017/ipab20170126.xml',
 '../data/app_bib_2017/ipab20170615.xml',
 '../data/app_bib_2017/ipab20170511.xml',
 '../data/app_bib_2017/ipab20170323.xml',
 '../data/app_bib_2017/ipab20170302.xml',
 '../data/app_bib_2017/ipab20170629.xml',
 '../data/app_bib_2017/ipab20170309.xml',
 '../data/app_bib_2017/ipab20171012.xml',
 '../data/app_bib_2017/ipab20170413.xml',
 '../data/app_bib_2017/ipab20170608.xml',
 '../data/app_bib_2017/ipab20170112.xml',
 '../data/app_bib_2017/ipab20171026.xml',
 '../data/app_bib_2017/ipab20170420.xml',
 '../data/app_bib_2017/ipab20170406.xml',
 '../data/app_bib_2017/ipab20170427.xml',
 '../data/app_bib_2017/ipab20170810.xml',
 '../data/app_bib_2017/ipab20171005.xml',
 '../data/app_bib_2017/ipab20170622.xml',
 '../data/app_bib_2017/ipab20170202.xml',
 '../data/app_bib_2017/ipab20171214.xml',
 '../data/app_bib_2017/ipab20170330.xml',
 '../data/app_bib_2017/ipab20170209.xml',
 '../data/app_bib_2017/ipab20171130.xml',
 '../data/app_bib_2017/ipab20170831.xml',
 '../data/app_bib_2017/ipab20171102.xml',
 '../data/app_bib_2017/ipab20171116.xml']

In [4]:
Files_grant

['../data/grant_bib_2012/ipgb20120501.xml',
 '../data/grant_bib_2012/ipgb20120306.xml',
 '../data/grant_bib_2012/ipgb20120508.xml',
 '../data/grant_bib_2012/ipgb20120821.xml',
 '../data/grant_bib_2012/ipgb20120605.xml',
 '../data/grant_bib_2012/ipgb20121127.xml',
 '../data/grant_bib_2012/ipgb20120313.xml',
 '../data/grant_bib_2012/ipgb20120918.xml',
 '../data/grant_bib_2012/ipgb20121120.xml',
 '../data/grant_bib_2012/ipgb20120925.xml',
 '../data/grant_bib_2012/ipgb20121009.xml',
 '../data/grant_bib_2012/ipgb20120807.xml',
 '../data/grant_bib_2012/ipgb20120522.xml',
 '../data/grant_bib_2012/ipgb20120612.xml',
 '../data/grant_bib_2012/ipgb20120911.xml',
 '../data/grant_bib_2012/ipgb20120103.xml',
 '../data/grant_bib_2012/ipgb20120703.xml',
 '../data/grant_bib_2012/ipgb20120131.xml',
 '../data/grant_bib_2012/ipgb20121106.xml',
 '../data/grant_bib_2012/ipgb20120731.xml',
 '../data/grant_bib_2012/ipgb20120327.xml',
 '../data/grant_bib_2012/ipgb20120904.xml',
 '../data/grant_bib_2012/ipgb20120814.xml',
 '../data/grant_bib_2012/ipgb20121030.xml',
 '../data/grant_bib_2012/ipgb20120117.xml',
 '../data/grant_bib_2012/ipgb20121002.xml',
 '../data/grant_bib_2012/ipgb20120529.xml',
 '../data/grant_bib_2012/ipgb20120417.xml',
 '../data/grant_bib_2012/ipgb20120228.xml',
 '../data/grant_bib_2012/ipgb20120124.xml',
 '../data/grant_bib_2012/ipgb20120828.xml',
 '../data/grant_bib_2012/ipgb20120710.xml',
 '../data/grant_bib_2012/ipgb20120214.xml',
 '../data/grant_bib_2012/ipgb20121204.xml',
 '../data/grant_bib_2012/ipgb20121211.xml',
 '../data/grant_bib_2012/ipgb20120110.xml',
 '../data/grant_bib_2012/ipgb20120626.xml',
 '../data/grant_bib_2012/ipgb20120724.xml',
 '../data/grant_bib_2012/ipgb20120207.xml',
 '../data/grant_bib_2012/ipgb20120403.xml',
 '../data/grant_bib_2012/ipgb20121218.xml',
 '../data/grant_bib_2012/ipgb20120410.xml',
 '../data/grant_bib_2012/ipgb20121225.xml',
 '../data/grant_bib_2012/ipgb20120424.xml',
 '../data/grant_bib_2012/ipgb20120717.xml',
 '../data/grant_bib_2012/ipgb20120515.xml',
 '../data/grant_bib_2012/ipgb20121113.xml',
 '../data/grant_bib_2012/ipgb20121023.xml',
 '../data/grant_bib_2012/ipgb20120221.xml',
 '../data/grant_bib_2012/ipgb20120320.xml',
 '../data/grant_bib_2012/ipgb20120619.xml',
 '../data/grant_bib_2012/ipgb20121016.xml']

In [4]:
list_app = []

col_names = [ 'c{0:02d}'.format(i) for i in range(3) ]

for file_app in Files_app:
    f_app = pd.read_table(file_app, header=None, names=col_names )
    list_app.append(f_app.as_matrix())

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
np_array_app = np.vstack(list_app)
big_frame = pd.DataFrame(np_array_app)

In [6]:
big_frame

                                                          0    1    2
0                    <?xml version="1.0" encoding="UTF-8"?>  NaN  NaN
1         <!DOCTYPE us-patent-application SYSTEM "us-pat...  NaN  NaN
2         <us-patent-application lang="EN" dtd-version="...  NaN  NaN
3         <us-bibliographic-data-application lang="EN" c...  NaN  NaN
4                                   <publication-reference>  NaN  NaN
5                                             <document-id>  NaN  NaN
6                                     <country>US</country>  NaN  NaN
7                      <doc-number>20170188504</doc-number>  NaN  NaN
8                                           <kind>A1</kind>  NaN  NaN
9                                     <date>20170706</date>  NaN  NaN
10                                           </document-id>  NaN  NaN
11                                 </publication-reference>  NaN  NaN
12              <application-reference appl-type="utility">  NaN  NaN
13                                            <document-id>  NaN  NaN
14                                    <country>US</country>  NaN  NaN
15                        <doc-number>14988955</doc-number>  NaN  NaN
16                                    <date>20160106</date>  NaN  NaN
17                                           </document-id>  NaN  NaN
18                                 </application-reference>  NaN  NaN
19        <us-application-series-code>14</us-application...  NaN  NaN
20                                   <classifications-ipcr>  NaN  NaN
21                                    <classification-ipcr>  NaN  NaN
22        <ipc-version-indicator><date>20060101</date></...  NaN  NaN
23           <classification-level>A</classification-level>  NaN  NaN
24                                     <section>A</section>  NaN  NaN
25                                        <class>01</class>  NaN  NaN
26                                   <subclass>B</subclass>  NaN  NaN
27                               <main-group>1</main-group>  NaN  NaN
28                                  <subgroup>02</subgroup>  NaN  NaN
29                     <symbol-position>F</symbol-position>  NaN  NaN
...                                                     ...  ...  ...
90632597                                      <addressbook>  NaN  NaN
90632598                      <last-name>Hansen</last-name>  NaN  NaN
90632599                   <first-name>Hans A.</first-name>  NaN  NaN
90632600                                          <address>  NaN  NaN
90632601                               <city>Zeeland</city>  NaN  NaN
90632602                                  <state>MI</state>  NaN  NaN
90632603                              <country>US</country>  NaN  NaN
90632604                                         </address>  NaN  NaN
90632605                                     </addressbook>  NaN  NaN
90632606                                        </inventor>  NaN  NaN
90632607                                       </inventors>  NaN  NaN
90632608                                      </us-parties>  NaN  NaN
90632609                                        <assignees>  NaN  NaN
90632610                                         <assignee>  NaN  NaN
90632611                                      <addressbook>  NaN  NaN
90632612           <orgname>Walters Gardens, Inc.</orgname>  NaN  NaN
90632613                                    <role>02</role>  NaN  NaN
90632614                                          <address>  NaN  NaN
90632615                               <city>Zeeland</city>  NaN  NaN
90632616                                  <state>MI</state>  NaN  NaN
90632617                              <country>US</country>  NaN  NaN
90632618                                         </address>  NaN  NaN
90632619                                     </addressbook>  NaN  NaN
90632620                                        </assignee>  NaN  NaN
90632621                                       </assignees>  NaN  NaN
90632622               </us-bibliographic-data-application>  NaN  NaN
90632623                           <abstract id="abstract">  NaN  NaN
90632624  <p id="p-0001" num="0000">The new and distinct...  NaN  NaN
90632625                                        </abstract>  NaN  NaN
90632626                           </us-patent-application>  NaN  NaN

[90632627 rows x 3 columns]

In [28]:
big_frame[1].count()

27

In [40]:
big_frame[~big_frame[1].isnull()]

,0,1,2
12292016,<orgname>THE REGENTS OF THE UNIVERSITY,"OF COLORADO, A BODY CORPORATE</orgname>",NaN
18097879,<orgname>THE HENRY M. JACKSON FOUNDATION FOR THE,"ADVANCEMENT OF MILITARY MEDICINE, INC.</orgname>",NaN
23130492,<orgname>YULONG COMPUTER TELECOMMUNICATION SCI...,"(SHENZHEN) CO., LTD.</orgname>",NaN
31612853,<orgname>KYONGGI UNIVERSITY INDUSTRY AND ACADEMIA,COOPERATION FOUNDATION</orgname>,NaN
47954849,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd.</orgname>",NaN
51264505,<orgname>Sema Plastik Kalip Ve Makine Sanayi V...,Ltd. Sti.</orgname>,NaN
55571002,<orgname>TOSHIBA INDUSTRIAL PRODUCTS AND SYSTEMS,CORPORATION</orgname>,NaN
59321490,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59396375,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59417828,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59417993,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59418801,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59418828,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59466381,<orgname>Shenzhen China Star Optoelectronics T...,"Co., Ltd</orgname>",NaN
59466393,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59466440,<orgname>Shenzhen China Star Optoelectronics T...,"Co., Ltd</orgname>",NaN
59466450,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59651931,<orgname>Shenzhen China Star Optoelectronics T...,"Co., Ltd.</orgname>",NaN
59655695,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd</orgname>",NaN
59756136,<orgname>Shenzhen China Star Optoelectronics T...,"Co., Ltd.</orgname>",NaN
64546758,<orgname>KING ABDULLAH UNIVERSITY OF SCIENCE AND,TECHNOLOGY</orgname>,NaN
68679862,"<orgname>The United States of America, as repr...","the Secretary, Department of Health &#x26; Hu...",NaN
68779364,<orgname>SANOVEL ILAC SANAYI VE TICARET,ANONIM SIRKETI</orgname>,NaN
71600372,<orgname>UNIVERSITY OF PITTSBURGH-OF THE COMMO...,SYSTEM OF HIGHER EDUCATION</orgname>,NaN
74227197,"<invention-title id=""d2e61"">Agrochemical Compo...",-disubstituted (Thio)urea for the Improvement ...,NaN
87785775,<orgname>Shenzhen China Star Optoelectronics T...,"Co., Ltd.</orgname>",NaN
87785785,<orgname>Wuhan China Star Optoelectronics Tech...,"Co., Ltd.</orgname>",NaN

In [41]:
big_frame[~big_frame[2].isnull()]

,0,1,2
73596670,<orgname>SHENYANG HUADE HIGH TECHNOLOGY,NaN,"ELECTRIC CO., LTD.</orgname>"

In [7]:
big_frame_app = big_frame.drop([1,2], axis = 1)

In [8]:
big_frame_app

                                                          0
0                    <?xml version="1.0" encoding="UTF-8"?>
1         <!DOCTYPE us-patent-application SYSTEM "us-pat...
2         <us-patent-application lang="EN" dtd-version="...
3         <us-bibliographic-data-application lang="EN" c...
4                                   <publication-reference>
5                                             <document-id>
6                                     <country>US</country>
7                      <doc-number>20170188504</doc-number>
8                                           <kind>A1</kind>
9                                     <date>20170706</date>
10                                           </document-id>
11                                 </publication-reference>
12              <application-reference appl-type="utility">
13                                            <document-id>
14                                    <country>US</country>
15                        <doc-number>14988955</doc-number>
16                                    <date>20160106</date>
17                                           </document-id>
18                                 </application-reference>
19        <us-application-series-code>14</us-application...
20                                   <classifications-ipcr>
21                                    <classification-ipcr>
22        <ipc-version-indicator><date>20060101</date></...
23           <classification-level>A</classification-level>
24                                     <section>A</section>
25                                        <class>01</class>
26                                   <subclass>B</subclass>
27                               <main-group>1</main-group>
28                                  <subgroup>02</subgroup>
29                     <symbol-position>F</symbol-position>
...                                                     ...
90632597                                      <addressbook>
90632598                      <last-name>Hansen</last-name>
90632599                   <first-name>Hans A.</first-name>
90632600                                          <address>
90632601                               <city>Zeeland</city>
90632602                                  <state>MI</state>
90632603                              <country>US</country>
90632604                                         </address>
90632605                                     </addressbook>
90632606                                        </inventor>
90632607                                       </inventors>
90632608                                      </us-parties>
90632609                                        <assignees>
90632610                                         <assignee>
90632611                                      <addressbook>
90632612           <orgname>Walters Gardens, Inc.</orgname>
90632613                                    <role>02</role>
90632614                                          <address>
90632615                               <city>Zeeland</city>
90632616                                  <state>MI</state>
90632617                              <country>US</country>
90632618                                         </address>
90632619                                     </addressbook>
90632620                                        </assignee>
90632621                                       </assignees>
90632622               </us-bibliographic-data-application>
90632623                           <abstract id="abstract">
90632624  <p id="p-0001" num="0000">The new and distinct...
90632625                                        </abstract>
90632626                           </us-patent-application>

[90632627 rows x 1 columns]

In [4]:
list_grant = []

col_names = [ 'c{0:02d}'.format(i) for i in range(2) ]

for file_grant in Files_grant:
    f_grant = pd.read_table(file_grant, header=None, names=col_names )
    list_grant.append(f_grant.as_matrix())

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
np_array_grant = np.vstack(list_grant)
Big_frame = pd.DataFrame(np_array_grant)

In [10]:
Big_frame[~Big_frame[1].isnull()]

,0,1
23368,<othercit>TDR6(FUKUYAMA Musical Instrument Cen...,</othercit>
12922820,"<invention-title id=""d2e71"">Driving-voltage ge...",having the same</invention-title>
13230846,"<invention-title id=""d2e92"">Device and method ...",</invention-title>
43672089,"<invention-title id=""d2e69"">R-F",e-B rare-earth sintered magnet and process for...
58924837,"<invention-title id=""d2e71"">Transmission metho...",system</invention-title>
122891906,"<invention-title id=""d2e53"">Link supportabilit...",communications system</invention-title>
129174611,"<othercit>Sekiguchi et al., &#x201c;Mutational...",</othercit>
129174623,"<othercit>Sekiguchi et al., &#x201c;Proteolyti...",</othercit>
129174653,"<othercit>Sekiguchi et al., &#x201c;Stimulatio...",</othercit>
129174659,"<othercit>Sekiguchi et al., &#x201c;Vaccinia t...",</othercit>
129174683,"<othercit>Shuman, &#x201c;Analysis of topoisom...",</othercit>
129174707,"<othercit>Shuman et al., &#x201c;Intramolecula...",</othercit>
150828870,"<invention-title id=""d2e51"">Method and system ...",secure network address translations</inventio...
158858497,"<invention-title id=""d2e71"">Content distributi...",</invention-title>
159011173,"<othercit>Amazon, &#x201c;Belkin Silicone Slee...",</othercit>
181449394,"<invention-title id=""d2e43"">Universal grignard",metathesis polymerization</invention-title>

In [11]:
big_frame_grant = Big_frame.drop(1, axis = 1)

In [12]:
big_frame_grant

                                                           0
0                     <?xml version="1.0" encoding="UTF-8"?>
1          <!DOCTYPE us-patent-grant SYSTEM "us-patent-gr...
2          <us-patent-grant lang="EN" dtd-version="v4.2 2...
3                              <us-bibliographic-data-grant>
4                                    <publication-reference>
5                                              <document-id>
6                                      <country>US</country>
7                          <doc-number>D0658346</doc-number>
8                                            <kind>S1</kind>
9                                      <date>20120501</date>
10                                            </document-id>
11                                  </publication-reference>
12                <application-reference appl-type="design">
13                                             <document-id>
14                                     <country>US</country>
15                         <doc-number>29385429</doc-number>
16                                     <date>20110214</date>
17                                            </document-id>
18                                  </application-reference>
19         <us-application-series-code>29</us-application...
20                                         <priority-claims>
21            <priority-claim sequence="01" kind="regional">
22                                     <country>EM</country>
23                    <doc-number>001229744-001</doc-number>
24                                     <date>20100813</date>
25                                         </priority-claim>
26                                        </priority-claims>
27                                        <us-term-of-grant>
28                     <length-of-grant>14</length-of-grant>
29                                       </us-term-of-grant>
...                                                      ...
183442302                                 <primary-examiner>
183442303                      <last-name>Nguyen</last-name>
183442304                    <first-name>Kiet T</first-name>
183442305                      <department>2881</department>
183442306                                </primary-examiner>
183442307                                       </examiners>
183442308                      <pct-or-regional-filing-data>
183442309                                      <document-id>
183442310                              <country>WO</country>
183442311         <doc-number>PCT/EP2006/012586</doc-number>
183442312                                    <kind>00</kind>
183442313                              <date>20061228</date>
183442314                                     </document-id>
183442315                                  <us-371c124-date>
183442316                              <date>20091215</date>
183442317                                 </us-371c124-date>
183442318                     </pct-or-regional-filing-data>
183442319                  <pct-or-regional-publishing-data>
183442320                                      <document-id>
183442321                              <country>WO</country>
183442322             <doc-number>WO2008/083694</doc-number>
183442323                                    <kind>A </kind>
183442324                              <date>20080717</date>
183442325                                     </document-id>
183442326                 </pct-or-regional-publishing-data>
183442327                     </us-bibliographic-data-grant>
183442328                           <abstract id="abstract">
183442329  <p id="p-0001" num="0000">Proposed is a proced...
183442330                                        </abstract>
183442331                                 </us-patent-grant>

[183442332 rows x 1 columns]

In [13]:
mask = big_frame_grant[0].str.contains('<publication-reference>')

add = [False, False, False]
add_df = pd.Series(add)

mask_pub = pd.concat([add_df, mask]).reset_index(drop = True)
mask_pub

0            False
1            False
2            False
3            False
4            False
5            False
6            False
7             True
8            False
9            False
10           False
11           False
12           False
13           False
14           False
15           False
16           False
17           False
18           False
19           False
20           False
21           False
22           False
23           False
24           False
25           False
26           False
27           False
28           False
29           False
             ...
183442305    False
183442306    False
183442307    False
183442308    False
183442309    False
183442310    False
183442311    False
183442312    False
183442313    False
183442314    False
183442315    False
183442316    False
183442317    False
183442318    False
183442319    False
183442320    False
183442321    False
183442322    False
183442323    False
183442324    False
183442325    False
183442326    False
183442327    False
183442328    False
183442329    False
183442330    False
183442331    False
183442332    False
183442333    False
183442334    False
Length: 183442335, dtype: bool

In [14]:
xml_pub = big_frame_grant[0].where(mask_pub).dropna(how = all)
xml_pub

7            <doc-number>D0658346</doc-number>
345          <doc-number>D0658347</doc-number>
722          <doc-number>D0658348</doc-number>
1228         <doc-number>D0658349</doc-number>
1693         <doc-number>D0658350</doc-number>
2051         <doc-number>D0658351</doc-number>
2286         <doc-number>D0658352</doc-number>
2918         <doc-number>D0658353</doc-number>
3342         <doc-number>D0658354</doc-number>
3718         <doc-number>D0658355</doc-number>
4174         <doc-number>D0658356</doc-number>
4849         <doc-number>D0658357</doc-number>
5266         <doc-number>D0658358</doc-number>
5710         <doc-number>D0658359</doc-number>
5959         <doc-number>D0658360</doc-number>
6267         <doc-number>D0658361</doc-number>
6655         <doc-number>D0658362</doc-number>
6911         <doc-number>D0658363</doc-number>
7447         <doc-number>D0658364</doc-number>
7703         <doc-number>D0658365</doc-number>
7879         <doc-number>D0658366</doc-number>
9725         <doc-number>D0658367</doc-number>
9934         <doc-number>D0658368</doc-number>
10097        <doc-number>D0658369</doc-number>
10277        <doc-number>D0658370</doc-number>
10444        <doc-number>D0658371</doc-number>
10633        <doc-number>D0658372</doc-number>
10929        <doc-number>D0658373</doc-number>
11232        <doc-number>D0658374</doc-number>
11600        <doc-number>D0658375</doc-number>
                           ...
183417623    <doc-number>08291482</doc-number>
183418789    <doc-number>08291483</doc-number>
183419594    <doc-number>08291484</doc-number>
183420120    <doc-number>08291485</doc-number>
183423507    <doc-number>08291486</doc-number>
183423728    <doc-number>08291487</doc-number>
183423976    <doc-number>08291488</doc-number>
183424337    <doc-number>08291489</doc-number>
183426172    <doc-number>08291490</doc-number>
183426528    <doc-number>08291491</doc-number>
183426804    <doc-number>08291492</doc-number>
183428556    <doc-number>08291493</doc-number>
183428911    <doc-number>08291494</doc-number>
183429095    <doc-number>08291495</doc-number>
183429789    <doc-number>08291496</doc-number>
183429985    <doc-number>08291497</doc-number>
183430960    <doc-number>08291498</doc-number>
183431749    <doc-number>08291499</doc-number>
183434234    <doc-number>08291500</doc-number>
183434714    <doc-number>08291501</doc-number>
183435262    <doc-number>08291502</doc-number>
183436200    <doc-number>08291503</doc-number>
183436490    <doc-number>08291504</doc-number>
183436854    <doc-number>08291505</doc-number>
183437068    <doc-number>08291506</doc-number>
183437377    <doc-number>08291507</doc-number>
183437697    <doc-number>08291508</doc-number>
183441230    <doc-number>08291509</doc-number>
183441847    <doc-number>08291510</doc-number>
183442084    <doc-number>08291511</doc-number>
Name: 0, Length: 277284, dtype: object

In [21]:
xml_pub_num = xml_pub.str[12:20]
xml_pub_df = pd.DataFrame(xml_pub_num)
xml_pub_df[1] = xml_pub_num.index.values.tolist()
xml_pub_df = xml_pub_df.reset_index(drop = True)
xml_pub_df

               0          1
0       D0658346          7
1       D0658347        345
2       D0658348        722
3       D0658349       1228
4       D0658350       1693
5       D0658351       2051
6       D0658352       2286
7       D0658353       2918
8       D0658354       3342
9       D0658355       3718
10      D0658356       4174
11      D0658357       4849
12      D0658358       5266
13      D0658359       5710
14      D0658360       5959
15      D0658361       6267
16      D0658362       6655
17      D0658363       6911
18      D0658364       7447
19      D0658365       7703
20      D0658366       7879
21      D0658367       9725
22      D0658368       9934
23      D0658369      10097
24      D0658370      10277
25      D0658371      10444
26      D0658372      10633
27      D0658373      10929
28      D0658374      11232
29      D0658375      11600
...          ...        ...
277254  08291482  183417623
277255  08291483  183418789
277256  08291484  183419594
277257  08291485  183420120
277258  08291486  183423507
277259  08291487  183423728
277260  08291488  183423976
277261  08291489  183424337
277262  08291490  183426172
277263  08291491  183426528
277264  08291492  183426804
277265  08291493  183428556
277266  08291494  183428911
277267  08291495  183429095
277268  08291496  183429789
277269  08291497  183429985
277270  08291498  183430960
277271  08291499  183431749
277272  08291500  183434234
277273  08291501  183434714
277274  08291502  183435262
277275  08291503  183436200
277276  08291504  183436490
277277  08291505  183436854
277278  08291506  183437068
277279  08291507  183437377
277280  08291508  183437697
277281  08291509  183441230
277282  08291510  183441847
277283  08291511  183442084

[277284 rows x 2 columns]

In [29]:
xml_pub_df_pat = xml_pub_df[~xml_pub_df[0].str.startswith('D') & ~xml_pub_df[0].str.startswith('P') & ~xml_pub_df[0].str.startswith('R')]

In [30]:
xml_pub_df_pat

               0          1
539     08166569     269357
540     08166570     270056
541     08166571     270356
542     08166572     271432
543     08166573     271923
544     08166574     272224
545     08166575     272701
546     08166576     273203
547     08166577     273542
548     08166578     274100
549     08166579     274490
550     08166580     274884
551     08166581     275159
552     08166582     275538
553     08166583     276071
554     08166584     276272
555     08166585     278043
556     08166586     278421
557     08166587     278808
558     08166588     279030
559     08166589     279392
560     08166590     279625
561     08166591     279995
562     08166592     280289
563     08166593     280594
564     08166594     280991
565     08166595     281551
566     08166596     282148
567     08166597     282554
568     08166598     283362
...          ...        ...
277254  08291482  183417623
277255  08291483  183418789
277256  08291484  183419594
277257  08291485  183420120
277258  08291486  183423507
277259  08291487  183423728
277260  08291488  183423976
277261  08291489  183424337
277262  08291490  183426172
277263  08291491  183426528
277264  08291492  183426804
277265  08291493  183428556
277266  08291494  183428911
277267  08291495  183429095
277268  08291496  183429789
277269  08291497  183429985
277270  08291498  183430960
277271  08291499  183431749
277272  08291500  183434234
277273  08291501  183434714
277274  08291502  183435262
277275  08291503  183436200
277276  08291504  183436490
277277  08291505  183436854
277278  08291506  183437068
277279  08291507  183437377
277280  08291508  183437697
277281  08291509  183441230
277282  08291510  183441847
277283  08291511  183442084

[253640 rows x 2 columns]

In [31]:
xml_pub_df_pat[0] = xml_pub_df_pat[0].str[1:8]

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
xml_pub_df_pat

              0          1
539     8166569     269357
540     8166570     270056
541     8166571     270356
542     8166572     271432
543     8166573     271923
544     8166574     272224
545     8166575     272701
546     8166576     273203
547     8166577     273542
548     8166578     274100
549     8166579     274490
550     8166580     274884
551     8166581     275159
552     8166582     275538
553     8166583     276071
554     8166584     276272
555     8166585     278043
556     8166586     278421
557     8166587     278808
558     8166588     279030
559     8166589     279392
560     8166590     279625
561     8166591     279995
562     8166592     280289
563     8166593     280594
564     8166594     280991
565     8166595     281551
566     8166596     282148
567     8166597     282554
568     8166598     283362
...         ...        ...
277254  8291482  183417623
277255  8291483  183418789
277256  8291484  183419594
277257  8291485  183420120
277258  8291486  183423507
277259  8291487  183423728
277260  8291488  183423976
277261  8291489  183424337
277262  8291490  183426172
277263  8291491  183426528
277264  8291492  183426804
277265  8291493  183428556
277266  8291494  183428911
277267  8291495  183429095
277268  8291496  183429789
277269  8291497  183429985
277270  8291498  183430960
277271  8291499  183431749
277272  8291500  183434234
277273  8291501  183434714
277274  8291502  183435262
277275  8291503  183436200
277276  8291504  183436490
277277  8291505  183436854
277278  8291506  183437068
277279  8291507  183437377
277280  8291508  183437697
277281  8291509  183441230
277282  8291510  183441847
277283  8291511  183442084

[253640 rows x 2 columns]

In [35]:
xml_pub_df_pat = xml_pub_df_pat.rename(columns={0: 'parsed'}).drop(1, axis = 1)

In [36]:
xml_pub_df_pat

         parsed
539     8166569
540     8166570
541     8166571
542     8166572
543     8166573
544     8166574
545     8166575
546     8166576
547     8166577
548     8166578
549     8166579
550     8166580
551     8166581
552     8166582
553     8166583
554     8166584
555     8166585
556     8166586
557     8166587
558     8166588
559     8166589
560     8166590
561     8166591
562     8166592
563     8166593
564     8166594
565     8166595
566     8166596
567     8166597
568     8166598
...         ...
277254  8291482
277255  8291483
277256  8291484
277257  8291485
277258  8291486
277259  8291487
277260  8291488
277261  8291489
277262  8291490
277263  8291491
277264  8291492
277265  8291493
277266  8291494
277267  8291495
277268  8291496
277269  8291497
277270  8291498
277271  8291499
277272  8291500
277273  8291501
277274  8291502
277275  8291503
277276  8291504
277277  8291505
277278  8291506
277279  8291507
277280  8291508
277281  8291509
277282  8291510
277283  8291511

[253640 rows x 1 columns]

In [37]:
xml_pub_df_pat.to_csv('../data/grant2012_all.csv')

In [ ]:
citation = pd.read_csv("../data/citations.csv")

In [9]:
mask = big_frame_app[0].str.contains('<application-reference appl-type="utility">')

add = [False, False, False]
add_df = pd.Series(add)

mask_pub = pd.concat([add_df, mask]).reset_index(drop = True)
mask_pub

0           False
1           False
2           False
3           False
4           False
5           False
6           False
7           False
8           False
9           False
10          False
11          False
12          False
13          False
14          False
15           True
16          False
17          False
18          False
19          False
20          False
21          False
22          False
23          False
24          False
25          False
26          False
27          False
28          False
29          False
            ...
90632600    False
90632601    False
90632602    False
90632603    False
90632604    False
90632605    False
90632606    False
90632607    False
90632608    False
90632609    False
90632610    False
90632611    False
90632612    False
90632613    False
90632614    False
90632615    False
90632616    False
90632617    False
90632618    False
90632619    False
90632620    False
90632621    False
90632622    False
90632623    False
90632624    False
90632625    False
90632626    False
90632627    False
90632628    False
90632629    False
Length: 90632630, dtype: bool

In [10]:
xml_app = big_frame_app[0].where(mask_pub).dropna(how = all)
xml_app

15          <doc-number>14988955</doc-number>
170         <doc-number>15299629</doc-number>
421         <doc-number>15239362</doc-number>
543         <doc-number>15462276</doc-number>
917         <doc-number>14998443</doc-number>
1055        <doc-number>14989324</doc-number>
1205        <doc-number>15394889</doc-number>
1549        <doc-number>15468355</doc-number>
1811        <doc-number>15397470</doc-number>
2050        <doc-number>15389705</doc-number>
2265        <doc-number>15315522</doc-number>
2583        <doc-number>15376045</doc-number>
2762        <doc-number>15394870</doc-number>
2864        <doc-number>15400508</doc-number>
3119        <doc-number>15320694</doc-number>
3309        <doc-number>15388262</doc-number>
3453        <doc-number>15466166</doc-number>
3623        <doc-number>15066891</doc-number>
3874        <doc-number>15038292</doc-number>
4017        <doc-number>15115888</doc-number>
4170        <doc-number>15338359</doc-number>
4297        <doc-number>15400857</doc-number>
4596        <doc-number>14985128</doc-number>
4746        <doc-number>14988031</doc-number>
4961        <doc-number>15144925</doc-number>
5121        <doc-number>15386079</doc-number>
5254        <doc-number>14987776</doc-number>
5345        <doc-number>15062132</doc-number>
5494        <doc-number>15404081</doc-number>
5754        <doc-number>14989373</doc-number>
                          ...
90623764    <doc-number>15498641</doc-number>
90624018    <doc-number>15593917</doc-number>
90624192    <doc-number>15591637</doc-number>
90624505    <doc-number>15531932</doc-number>
90624823    <doc-number>15155244</doc-number>
90625007    <doc-number>15582708</doc-number>
90625433    <doc-number>15419526</doc-number>
90625753    <doc-number>15522429</doc-number>
90626041    <doc-number>15481451</doc-number>
90626289    <doc-number>15667032</doc-number>
90626623    <doc-number>15291313</doc-number>
90626819    <doc-number>15593168</doc-number>
90627072    <doc-number>15150783</doc-number>
90627196    <doc-number>15523185</doc-number>
90627346    <doc-number>15153348</doc-number>
90627500    <doc-number>15595194</doc-number>
90627724    <doc-number>15535027</doc-number>
90627969    <doc-number>15590591</doc-number>
90628150    <doc-number>15526477</doc-number>
90628446    <doc-number>15528161</doc-number>
90628634    <doc-number>15664599</doc-number>
90628886    <doc-number>15586544</doc-number>
90629195    <doc-number>15291293</doc-number>
90629361    <doc-number>15291348</doc-number>
90629527    <doc-number>15627615</doc-number>
90629799    <doc-number>15154461</doc-number>
90630073    <doc-number>15533394</doc-number>
90630276    <doc-number>15662399</doc-number>
90630393    <doc-number>15583760</doc-number>
90630686    <doc-number>15529761</doc-number>
Name: 0, Length: 373926, dtype: object

In [14]:
xml_app_num = xml_app.str[12:20]
xml_app_df = pd.DataFrame(xml_app_num)
xml_app_df[1] = xml_app_num.index.values.tolist()
xml_app_df = xml_app_df.reset_index(drop = True)
xml_app_df

               0         1
0       14988955        15
1       15299629       170
2       15239362       421
3       15462276       543
4       14998443       917
5       14989324      1055
6       15394889      1205
7       15468355      1549
8       15397470      1811
9       15389705      2050
10      15315522      2265
11      15376045      2583
12      15394870      2762
13      15400508      2864
14      15320694      3119
15      15388262      3309
16      15466166      3453
17      15066891      3623
18      15038292      3874
19      15115888      4017
20      15338359      4170
21      15400857      4297
22      14985128      4596
23      14988031      4746
24      15144925      4961
25      15386079      5121
26      14987776      5254
27      15062132      5345
28      15404081      5494
29      14989373      5754
...          ...       ...
373896  15498641  90623764
373897  15593917  90624018
373898  15591637  90624192
373899  15531932  90624505
373900  15155244  90624823
373901  15582708  90625007
373902  15419526  90625433
373903  15522429  90625753
373904  15481451  90626041
373905  15667032  90626289
373906  15291313  90626623
373907  15593168  90626819
373908  15150783  90627072
373909  15523185  90627196
373910  15153348  90627346
373911  15595194  90627500
373912  15535027  90627724
373913  15590591  90627969
373914  15526477  90628150
373915  15528161  90628446
373916  15664599  90628634
373917  15586544  90628886
373918  15291293  90629195
373919  15291348  90629361
373920  15627615  90629527
373921  15154461  90629799
373922  15533394  90630073
373923  15662399  90630276
373924  15583760  90630393
373925  15529761  90630686

[373926 rows x 2 columns]

In [15]:
xml_app_df = xml_app_df.rename(columns={0: 'app_id'}).drop(1, axis = 1)

In [16]:
xml_app_df

          app_id
0       14988955
1       15299629
2       15239362
3       15462276
4       14998443
5       14989324
6       15394889
7       15468355
8       15397470
9       15389705
10      15315522
11      15376045
12      15394870
13      15400508
14      15320694
15      15388262
16      15466166
17      15066891
18      15038292
19      15115888
20      15338359
21      15400857
22      14985128
23      14988031
24      15144925
25      15386079
26      14987776
27      15062132
28      15404081
29      14989373
...          ...
373896  15498641
373897  15593917
373898  15591637
373899  15531932
373900  15155244
373901  15582708
373902  15419526
373903  15522429
373904  15481451
373905  15667032
373906  15291313
373907  15593168
373908  15150783
373909  15523185
373910  15153348
373911  15595194
373912  15535027
373913  15590591
373914  15526477
373915  15528161
373916  15664599
373917  15586544
373918  15291293
373919  15291348
373920  15627615
373921  15154461
373922  15533394
373923  15662399
373924  15583760
373925  15529761

[373926 rows x 1 columns]

In [17]:
xml_app_df.to_csv('../data/application2017_all.csv')